export interface AuditQuestion {
  id: string;
  section: string;
  sectionIndex: number;
  questionIndex: number;
  text: string;
  followUp?: string;
  type: "text" | "number" | "scale";
  kind?: "main" | "follow_up";
}

export const AUDIT_SECTIONS = [
  "Alignment & Trust",
  "Reality Check",
  "Blind Spots & Friction",
  "Priority & Commitment",
];

export const AUDIT_QUESTIONS: AuditQuestion[] = [
  // Section 0: Alignment & Trust
  {
    id: "p1",
    section: "Alignment & Trust",
    sectionIndex: 0,
    questionIndex: 0,
    type: "text",
    kind: "main",
    text: "What are you trying to make better in this season of life or work — and why does it matter now?",
  },
  {
    id: "p2",
    section: "Alignment & Trust",
    sectionIndex: 0,
    questionIndex: 1,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: if this went well in the next 90 days, what would be meaningfully different in your actual life, not just in your head?",
  },
  {
    id: "r1",
    section: "Alignment & Trust",
    sectionIndex: 0,
    questionIndex: 2,
    type: "text",
    kind: "main",
    text: "Where are you already showing up well right now — the part of your life or work that feels most solid, responsible, or self-respecting?",
  },
  {
    id: "r2",
    section: "Alignment & Trust",
    sectionIndex: 0,
    questionIndex: 3,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: what are you doing consistently that helps create that stability?",
  },
  {
    id: "te1",
    section: "Alignment & Trust",
    sectionIndex: 0,
    questionIndex: 4,
    type: "text",
    kind: "main",
    text: "What responsibilities or priorities feel genuinely non-negotiable for you right now?",
  },
  {
    id: "te2",
    section: "Alignment & Trust",
    sectionIndex: 0,
    questionIndex: 5,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: which of those are truly yours, and which are things you keep carrying by default, guilt, or old agreement?",
  },

  // Section 1: Reality Check
  {
    id: "te3",
    section: "Reality Check",
    sectionIndex: 1,
    questionIndex: 0,
    type: "scale",
    kind: "main",
    text: "On a scale of 1–10, how aligned is your current week with what you just said matters most?",
  },
  {
    id: "te4",
    section: "Reality Check",
    sectionIndex: 1,
    questionIndex: 1,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: what does your calendar, energy, or attention do that proves that number is real?",
  },
  {
    id: "mb1",
    section: "Reality Check",
    sectionIndex: 1,
    questionIndex: 2,
    type: "text",
    kind: "main",
    text: "Walk me through a recent normal week. Where does your time, energy, and attention actually go?",
  },
  {
    id: "mb2",
    section: "Reality Check",
    sectionIndex: 1,
    questionIndex: 3,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: what keeps getting more of you than it deserves?",
  },
  {
    id: "h1",
    section: "Reality Check",
    sectionIndex: 1,
    questionIndex: 4,
    type: "text",
    kind: "main",
    text: "How sustainable does your current pace feel physically and mentally?",
  },
  {
    id: "h2",
    section: "Reality Check",
    sectionIndex: 1,
    questionIndex: 5,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: what are the clearest signs your body, mood, or focus is paying for the way you are operating?",
  },

  // Section 2: Blind Spots & Friction
  {
    id: "r3",
    section: "Blind Spots & Friction",
    sectionIndex: 2,
    questionIndex: 0,
    type: "scale",
    kind: "main",
    text: "On a scale of 1–10, how supported and candid are the people around you with you?",
  },
  {
    id: "r4",
    section: "Blind Spots & Friction",
    sectionIndex: 2,
    questionIndex: 1,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: where might comfort, loyalty, or image-management be keeping you from hearing what you need to hear?",
  },
  {
    id: "e1",
    section: "Blind Spots & Friction",
    sectionIndex: 2,
    questionIndex: 2,
    type: "text",
    kind: "main",
    text: "What pattern keeps repeating even though you already know better?",
  },
  {
    id: "e2",
    section: "Blind Spots & Friction",
    sectionIndex: 2,
    questionIndex: 3,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: what do you usually blame on circumstances that is at least partly a choice, avoidance, or weak system?",
  },
  {
    id: "p3",
    section: "Blind Spots & Friction",
    sectionIndex: 2,
    questionIndex: 4,
    type: "scale",
    kind: "main",
    text: "On a scale of 1–10, how honest have you been with yourself about the real bottleneck right now?",
  },
  {
    id: "p4",
    section: "Blind Spots & Friction",
    sectionIndex: 2,
    questionIndex: 5,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: if someone who knows you well answered for you, what would they say you are avoiding, protecting, or pretending not to see?",
  },

  // Section 3: Priority & Commitment
  {
    id: "mb3",
    section: "Priority & Commitment",
    sectionIndex: 3,
    questionIndex: 0,
    type: "scale",
    kind: "main",
    text: "On a scale of 1–10, how clear are you on the one priority that should lead your next 90 days?",
  },
  {
    id: "mb4",
    section: "Priority & Commitment",
    sectionIndex: 3,
    questionIndex: 1,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: what keeps you from committing to that priority cleanly?",
  },
  {
    id: "e3",
    section: "Priority & Commitment",
    sectionIndex: 3,
    questionIndex: 2,
    type: "scale",
    kind: "main",
    text: "On a scale of 1–10, how much do your current environment and systems support disciplined follow-through?",
  },
  {
    id: "e4",
    section: "Priority & Commitment",
    sectionIndex: 3,
    questionIndex: 3,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: what is the smallest structural change that would make the right action easier this week?",
  },
  {
    id: "h3",
    section: "Priority & Commitment",
    sectionIndex: 3,
    questionIndex: 4,
    type: "text",
    kind: "main",
    text: "If you had to choose one change that would improve everything else, what would it be?",
  },
  {
    id: "h4",
    section: "Priority & Commitment",
    sectionIndex: 3,
    questionIndex: 5,
    type: "text",
    kind: "follow_up",
    text: "Follow-up: what are you willing to stop, start, or say no to so that choice becomes real?",
  },
];
